### ISSUE TITLE
Submodule sync/update based on repo version

### ISSUE THREAD

**Issue by rinor** [DavidArayan/cardano-node#1]
```sh
git submodule sync && \
git submodule update --init && \
```
have to be done after checkout so the submodule(s) are synced to the version needed on the checkout tag/branch.

The other changes are just optimizations to trim some time/space on git operations and can be safely ignored.

**From:**
https://github.com/DavidArayan/cardano-node/blob/5386469f935aea9b2703102fbc62bf6912dcaabd/jormungandr-alpine/Dockerfile#L33-L37

**To:**
```sh
	# Pull the cardano-node repository, checkout the specific commit and build
	git clone --depth 1 ${REPO} src && \
	cd src && \
	git fetch --depth 1 --tags && \
	git checkout tags/v${REPO_VERSION} && \
	git submodule sync && \
	git submodule update --init && \
	cargo build --release && \ 
```

**Comment by DavidArayan** [comment]
Hello @rinor, thank you for the improvement. I'm testing it now and will update the build in DockerHub soon, cheers!

**Comment by DavidArayan** [comment]
I've tested and merged the changes as part of [Release rc-1](https://github.com/DavidArayan/cardano-node/releases/tag/0.2.3-rc1). Build will be available in DockerHub soon. Thank you for your contribution!
